export { default as HeroSection } from './HeroSection'
export { default as HowItWorksSection } from './HowItWorksSection'
export { default as BenefitsSection } from './BenefitsSection'
export { default as StatsSection } from './StatsSection'
export { default as CTASection } from './CTASection'
